{% set name = "qcs-api-client" %}
{% set version = "0.21.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 093bef9d1c735da0f3caf646e28224184a1c2f6f90257bdc675c6509c496fce2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=1.0
  run:
    - attrs >=21.3.0,<22.0.0
    - httpx >=0.23.0,<0.24.0
    - iso8601 >=1.0.2,<2.0.0
    - pydantic >=1.7.2,<2.0.0
    - pyjwt >=2.4.0,<3.0.0
    - python >=3.6
    - python-dateutil >=2.8.1,<3.0.0
    - retrying >=1.3.3,<2.0.0
    - rfc3339 >=6.2.0,<7.0.0
    - toml >=0.10.2,<0.11.0

test:
  imports:
    - qcs_api_client
    - qcs_api_client.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rigetti/qcs-api-client-python
  summary: A client library for accessing the Rigetti QCS API
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://qcs-api-client-python.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - BastianZim
