{% set name = "qcs-api-client" %}
{% set version = "0.21.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d219aaef49eb6f515b601467f6c85f20ca52f788d90b3052775e6d12b2f57466

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=1.0
  run:
    - attrs ^21.3.0
    - httpx ^0.23.0
    - iso8601 ^1.0.2
    - pydantic ^1.7.2
    - pyjwt ^2.4.0
    - python >=3.6
    - python-dateutil ^2.8.1
    - retrying ^1.3.3
    - rfc3339 ^6.2
    - toml ^0.10.2

test:
  imports:
    - qcs_api_client
    - qcs_api_client.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rigetti/qcs-api-client-python
  summary: A client library for accessing the Rigetti QCS API
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://qcs-api-client-python.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - BastianZim
