{% set name = "qcs-api-client" %}
{% set version = "0.20.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qcs-api-client-{{ version }}.tar.gz
  sha256: d8ceabcdc323c8f205caf56e541b7fdb289a504ab09939b0e065940155c66940

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry >=1.0
  run:
    - attrs >=20.1.0,<21.0.0
    - httpx >=0.15.0,<0.16.0
    - iso8601 >=0.1.13,<0.2.0
    - pydantic >=1.7.2,<2.0.0
    - pyjwt >=1.7.1,<2.0.0
    - python >=3.6,<4.0
    - python-dateutil >=2.8.1,<3.0.0
    - retrying >=1.3.3,<2.0.0
    - rfc3339 >=6.2,<7.0
    - toml >=0.10.2,<0.11.0

test:
  imports:
    - qcs_api_client
    - qcs_api_client.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rigetti/qcs-api-client-python
  summary: A client library for accessing the Rigetti QCS API
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://qcs-api-client-python.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - BastianZim
